IO.puts "Final exercise"
IO.puts "\nFloat 1234.5678 to string = #{Float.to_string(1234.5678, decimals: 2)}"
# IO.puts "\nGet all system env variables = #{System.get_env()}"
IO.puts "\nGet system PATH env variable value = #{System.get_env("PATH")}"
IO.puts "\nFile extension = #{Path.extname("mnf2.exs")}"
IO.inspect "\nCurrent Working Directory = #{File.cwd!()}"
# IO.puts "\nJSON String to json = #{JSON.decode(JSON.decode("{\"result\":\"this will be an Elixir result\"}"))}"
# IO.puts "\nExecute shell command - \n\n#{System.cmd("ls", ["-al"])}"
IO.inspect "\nExecute shell command 2 - \n#{System.cmd "echo", ["hello world"]}"
